[package]
name = "rs-poseidon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = [
  "staticlib", # Ensure it gets compiled as a (static) C library
  "cdylib",    # If you want a shared/dynamic C library (advanced)
  "lib",       # For downstream Rust dependents: `examples/`, `tests/` etc.
]

[dependencies]
ark-ff = { version = "0.3.0", features = ["std"] }
ark-bn254 = { version = "0.3.0" }
ruint = { version = "1.7.0", features = ["serde", "num-bigint", "ark-ff"] }
serde = "1.0.156"
serde_json = "1.0.94"
once_cell = "1.17.1"
num-traits = "0.2.15"
num-bigint = { version = "0.4", default-features = false, features = ["rand"] }
